services:

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION:-3.22}
    container_name: nginx
    hostname: nginx
    restart: always

    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - TZ=${TZ:-UTC}
      - NGINX_VERSION=${NGINX_VERSION:-1.29.4}

    ports:
      - "443:443"

    networks:
      - inception_network

    volumes:
      - wordpress_data:/var/www/html

    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 3s
      retries: 3

    depends_on:
      mariadb:
        condition: service_healthy
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_started
      static_site:
        condition: service_started


  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    hostname: mariadb
    restart: always

    secrets:
      - db_root_password
      - db_password

    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USERNAME}
      - TZ=${TZ:-UTC}
      - ALPINE_VERSION=${ALPINE_VERSION:-3.22}
      - VOLUME_DIR=${VOLUME_DIR:-./data}/mariadb

    volumes:
      - mariadb_data:/var/lib/mysql/

    ports:
      - "${DB_PORT:-3306}"
    networks:
      - inception_network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 30s

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    hostname: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${DB_USERNAME}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_ADMIN_PASSWORD_FILE=${WORDPRESS_ADMIN_PASSWORD_FILE}
      - WORDPRESS_SITE_TITLE=${WORDPRESS_SITE_TITLE}
      - WORDPRESS_GUEST_USER=${WORDPRESS_GUEST_USER}
      - WORDPRESS_GUEST_EMAIL=${WORDPRESS_GUEST_EMAIL}
      - WORDPRESS_GUEST_PASSWORD_FILE=${WORDPRESS_GUEST_PASSWORD_FILE}
      - TZ=${TZ:-UTC}

    secrets:
      - db_password
      - wordpress_admin_password
      - wordpress_guest_password

    ports:
      - "9000"

    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm83 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    hostname: ftp
    restart: always
    depends_on:
      wordpress:
        condition: service_started
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "21"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

    environment:
      - FTP_USER=${FTP_USER}
      - TZ=${TZ:-UTC}

    ports:
      - "21:21"
      - "30000-30009:30000-30009"

    secrets:
      - ftp_password

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception_network

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    hostname: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      interval: 10s
      timeout: 3s
      retries: 3

    networks:
      - inception_network

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    hostname: adminer
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    environment:
      - TZ=${TZ:-UTC}
      - ALPINE_VERSION=${ALPINE_VERSION:-3.22}

    ports:
      - "8080"

    networks:
      - inception_network

  static_site:
    build:
      context: ./requirements/bonus/static_site
      dockerfile: Dockerfile
    container_name: static_site
    hostname: static_site
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - TZ=${TZ:-UTC}
      - ALPINE_VERSION=${ALPINE_VERSION:-3.22}

    ports:
      - "4321"

    networks:
      - inception_network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DIR:-./data}/mariadb/
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_DIR:-./data}/wordpress/

secrets:
  db_root_password:
    file: ./${DB_ROOT_PASSWORD_FILE}
  db_password:
    file: ./${DB_PASSWORD_FILE}
  wordpress_admin_password:
    file: ./${WORDPRESS_ADMIN_PASSWORD_FILE}
  wordpress_guest_password:
    file: ./${WORDPRESS_GUEST_PASSWORD_FILE}
  ftp_password:
    file: ./${FTP_PASSWORD_FILE}

# Redes
networks:
  inception_network:
    driver: bridge
