# Not allow anonymous login
anonymous_enable=NO

# Allow local users to log in
local_enable=YES

# Allow write commands for local users
write_enable=YES

# Mask for file permissions
local_umask=002

# Logs and messages
dirmessage_enable=YES
xferlog_enable=YES
connect_from_port_20=YES

# Chroot jail for local users
chroot_local_user=YES
allow_writeable_chroot=YES

# Passive mode settings
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
pasv_address=0.0.0.0

# PAM configuration
pam_service_name=vsftpd

# Disable SSL
ssl_enable=NO


seccomp_sandbox=NO
