[PHP]
max_execution_time = 300
memory_limit = 256M
post_max_size = 64M
upload_max_filesize = 64M
expose_php = Off
cgi.fix_pathinfo = 0
error_log = /proc/self/fd/2
log_errors = On

[Date]
date.timezone = "UTC"

[opcache]
opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=2
opcache.fast_shutdown=1S
